// Mock user data for development and testing
export const mockUsers: User[] = [
  {
    id: "U001",
    name: "Admin User",
    email: "admin@esoft.lk",
    password: "password123",
    role: "admin",
    department: "Administration",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-01T10:30:00Z",
  },
  {
    id: "U002",
    name: "Kavindu Perera",
    email: "kavindu.perera@esoft.lk",
    password: "password123",
    role: "student",
    department: "School of Computing",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-02T14:45:00Z",
  },
  {
    id: "U003",
    name: "Dr. Nimal Perera",
    email: "nimal.perera@esoft.lk",
    password: "password123",
    role: "lecturer",
    department: "School of Computing",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-03T09:15:00Z",
  },
  {
    id: "U004",
    name: "Sanduni Fernando",
    email: "sanduni.fernando@esoft.lk",
    password: "password123",
    role: "student",
    department: "School of Management & Law",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-04T11:20:00Z",
  },
  {
    id: "U005",
    name: "Dr. Chamari de Silva",
    email: "chamari.desilva@esoft.lk",
    password: "password123",
    role: "lecturer",
    department: "School of Sciences",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-05T16:10:00Z",
  },
  {
    id: "U006",
    name: "Nuwan Silva",
    email: "nuwan.silva@esoft.lk",
    password: "password123",
    role: "student",
    department: "School of Engineering",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-06T12:00:00Z",
  },
  {
    id: "U007",
    name: "Dr. Mahesh Silva",
    email: "mahesh.silva@esoft.lk",
    password: "password123",
    role: "lecturer",
    department: "School of Engineering",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-07T15:30:00Z",
  },
  {
    id: "U008",
    name: "Tharushi Weerasinghe",
    email: "tharushi.weerasinghe@esoft.lk",
    password: "password123",
    role: "student",
    department: "School of Life Science",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-08T09:45:00Z",
  },
  {
    id: "U009",
    name: "Dr. Anjali Weerasinghe",
    email: "anjali.weerasinghe@esoft.lk",
    password: "password123",
    role: "lecturer",
    department: "School of Life Science",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-09T14:20:00Z",
  },
  {
    id: "U010",
    name: "Hasini de Silva",
    email: "hasini.desilva@esoft.lk",
    password: "password123",
    role: "student",
    department: "School of Sciences",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-10T13:30:00Z",
  },
  {
    id: "U011",
    name: "Dr. Ruwan Jayawardena",
    email: "ruwan.jayawardena@esoft.lk",
    password: "password123",
    role: "lecturer",
    department: "School of Art & Design",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-11T17:00:00Z",
  },
  {
    id: "U012",
    name: "Kasun Wijesinghe",
    email: "kasun.wijesinghe@esoft.lk",
    password: "password123",
    role: "student",
    department: "School of Engineering",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-12T11:45:00Z",
  },
  {
    id: "U013",
    name: "Dilini Gamage",
    email: "dilini.gamage@esoft.lk",
    password: "password123",
    role: "student",
    department: "School of Computing",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-13T08:55:00Z",
  },
  {
    id: "U014",
    name: "Supun Ratnayake",
    email: "supun.ratnayake@esoft.lk",
    password: "password123",
    role: "student",
    department: "School of Management & Law",
    profileImage: "/placeholder.svg?height=40&width=40",
    lastLogin: "2023-09-14T15:10:00Z",
  },
];


// Export a function to find a user by email (case-insensitive)
export function findUserByEmail(email: string) {
  return mockUsers.find((user) => user.email.toLowerCase() === email.toLowerCase())
}

// Export a function to find a user by ID
export function findUserById(id: string) {
  return mockUsers.find((user) => user.id === id)
}

